#!/usr/bin/env bash
#
# Publish the appcast commit sitting on HEAD.
#
# `main` is branch-protected. An admin can push to it directly, which is the
# fast path; if that is refused — protection tightened, or this is not an
# admin's machine — open a PR instead, rather than leaving a release published
# with no matching feed entry.
#
# Split out of release.sh so this path can be exercised on its own: the direct
# push almost always succeeds, so the fallback would otherwise only ever run
# for the first time during a real release.
#
# Usage:
#   scripts/publish-appcast.sh v1.4.0
#
set -euo pipefail

TAG="${1:?usage: publish-appcast.sh <tag>}"

fail() { printf '\033[31merror: %s\033[0m\n' "$*" >&2; exit 1; }

# The fallback resets the branch back to origin/main once the commit is safely
# on a remote branch. That discards tracked modifications, so refuse to run
# unless there are none to lose.
[ -z "$(git status --porcelain --untracked-files=no)" ] \
  || fail "working tree has uncommitted changes to tracked files"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
[ "$BRANCH" = "main" ] || fail "expected to be on main, not '$BRANCH'"

git fetch -q origin main
AHEAD="$(git rev-list --count origin/main..HEAD)"
[ "$AHEAD" -ge 1 ] || fail "nothing to publish — HEAD is not ahead of origin/main"

if git push -q origin main 2>/dev/null; then
  echo "   appcast pushed to main"
  exit 0
fi

APPCAST_BRANCH="chore/appcast-$TAG"
git push -q origin "HEAD:$APPCAST_BRANCH"
PR_URL="$(gh pr create --head "$APPCAST_BRANCH" \
  --title "chore: appcast entry for $TAG" \
  --body "Generated by scripts/release.sh for $TAG. Merging this publishes the update feed.")"

# The commit is on the remote branch now, so drop it locally and leave main
# exactly level with origin — no half-applied state to clean up by hand.
git reset -q --hard origin/main

echo "   main is protected — opened $PR_URL"
echo "   NOTE: Sparkle will not offer $TAG until that PR is merged."
